{
  error: {
    message: 'nodemailer.createTransporter is not a function',
    stack: 'TypeError: nodemailer.createTransporter is not a function\n' +
      '    at EmailService.init (C:\\Users\\Admin\\Desktop\\AcademicAlly\\server\\src\\services\\emailService.js:36:39)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)',
    name: 'TypeError'
  },
  level: 'error',
  message: 'Failed to initialize email service:',
  timestamp: '2025-06-22 23:02:41'
}
{
  '0': 'r',
  '1': 'e',
  '2': 'a',
  '3': 's',
  '4': 'o',
  '5': 'n',
  '6': ':',
  error: Promise {
    <rejected> MongooseError: Connection.prototype.close() no longer accepts a callback
        at NativeConnection.close (C:\Users\Admin\Desktop\AcademicAlly\server\node_modules\mongoose\lib\connection.js:1205:11)
        at Server.<anonymous> (C:\Users\Admin\Desktop\AcademicAlly\server\server.js:298:25)
        at Object.onceWrapper (node:events:632:28)
        at Server.emit (node:events:530:35)
        at emitCloseNT (node:net:2418:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
  },
  level: 'error',
  message: 'Unhandled Rejection at:',
  timestamp: '2025-06-22 23:13:07'
}
{
  '0': 'r',
  '1': 'e',
  '2': 'a',
  '3': 's',
  '4': 'o',
  '5': 'n',
  '6': ':',
  error: Promise {
    <rejected> MongooseError: Connection.prototype.close() no longer accepts a callback
        at NativeConnection.close (C:\Users\Admin\Desktop\AcademicAlly\server\node_modules\mongoose\lib\connection.js:1205:11)
        at Server.<anonymous> (C:\Users\Admin\Desktop\AcademicAlly\server\server.js:298:25)
        at Object.onceWrapper (node:events:632:28)
        at Server.emit (node:events:530:35)
        at emitCloseNT (node:net:2418:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
  },
  level: 'error',
  message: 'Unhandled Rejection at:',
  timestamp: '2025-06-22 23:16:21'
}
{
  '0': 'r',
  '1': 'e',
  '2': 'a',
  '3': 's',
  '4': 'o',
  '5': 'n',
  '6': ':',
  error: Promise {
    <rejected> MongooseError: Connection.prototype.close() no longer accepts a callback
        at NativeConnection.close (C:\Users\Admin\Desktop\AcademicAlly\server\node_modules\mongoose\lib\connection.js:1205:11)
        at Server.<anonymous> (C:\Users\Admin\Desktop\AcademicAlly\server\server.js:298:25)
        at Object.onceWrapper (node:events:632:28)
        at Server.emit (node:events:530:35)
        at emitCloseNT (node:net:2418:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
  },
  level: 'error',
  message: 'Unhandled Rejection at:',
  timestamp: '2025-06-23 00:45:35'
}
{
  '0': 'r',
  '1': 'e',
  '2': 'a',
  '3': 's',
  '4': 'o',
  '5': 'n',
  '6': ':',
  error: Promise {
    <rejected> MongooseError: Connection.prototype.close() no longer accepts a callback
        at NativeConnection.close (C:\Users\Admin\Desktop\AcademicAlly\server\node_modules\mongoose\lib\connection.js:1205:11)
        at Server.<anonymous> (C:\Users\Admin\Desktop\AcademicAlly\server\server.js:298:25)
        at Object.onceWrapper (node:events:632:28)
        at Server.emit (node:events:530:35)
        at emitCloseNT (node:net:2418:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
  },
  level: 'error',
  message: 'Unhandled Rejection at:',
  timestamp: '2025-06-23 00:51:32'
}
{
  '0': 'r',
  '1': 'e',
  '2': 'a',
  '3': 's',
  '4': 'o',
  '5': 'n',
  '6': ':',
  error: Promise {
    <rejected> MongooseError: Connection.prototype.close() no longer accepts a callback
        at NativeConnection.close (C:\Users\Admin\Desktop\AcademicAlly\node_modules\mongoose\lib\connection.js:1205:11)
        at Server.<anonymous> (C:\Users\Admin\Desktop\AcademicAlly\server\server.js:298:25)
        at Object.onceWrapper (node:events:632:28)
        at Server.emit (node:events:530:35)
        at emitCloseNT (node:net:2418:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
  },
  level: 'error',
  message: 'Unhandled Rejection at:',
  timestamp: '2025-06-23 01:17:00'
}
{
  '0': 'r',
  '1': 'e',
  '2': 'a',
  '3': 's',
  '4': 'o',
  '5': 'n',
  '6': ':',
  error: Promise {
    <rejected> MongooseError: Connection.prototype.close() no longer accepts a callback
        at NativeConnection.close (C:\Users\Admin\Desktop\AcademicAlly\node_modules\mongoose\lib\connection.js:1205:11)
        at Server.<anonymous> (C:\Users\Admin\Desktop\AcademicAlly\server\server.js:298:25)
        at Object.onceWrapper (node:events:632:28)
        at Server.emit (node:events:530:35)
        at emitCloseNT (node:net:2418:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
  },
  level: 'error',
  message: 'Unhandled Rejection at:',
  timestamp: '2025-06-23 01:21:55'
}
{
  '0': 'r',
  '1': 'e',
  '2': 'a',
  '3': 's',
  '4': 'o',
  '5': 'n',
  '6': ':',
  error: Promise {
    <rejected> MongooseError: Connection.prototype.close() no longer accepts a callback
        at NativeConnection.close (C:\Users\Admin\Desktop\AcademicAlly\node_modules\mongoose\lib\connection.js:1205:11)
        at Server.<anonymous> (C:\Users\Admin\Desktop\AcademicAlly\server\server.js:298:25)
        at Object.onceWrapper (node:events:632:28)
        at Server.emit (node:events:530:35)
        at emitCloseNT (node:net:2418:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
  },
  level: 'error',
  message: 'Unhandled Rejection at:',
  timestamp: '2025-06-23 01:26:38'
}
{
  '0': 'r',
  '1': 'e',
  '2': 'a',
  '3': 's',
  '4': 'o',
  '5': 'n',
  '6': ':',
  error: Promise {
    <rejected> MongooseError: Connection.prototype.close() no longer accepts a callback
        at NativeConnection.close (C:\Users\Admin\Desktop\AcademicAlly\node_modules\mongoose\lib\connection.js:1205:11)
        at Server.<anonymous> (C:\Users\Admin\Desktop\AcademicAlly\server\server.js:298:25)
        at Object.onceWrapper (node:events:632:28)
        at Server.emit (node:events:530:35)
        at emitCloseNT (node:net:2418:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
  },
  level: 'error',
  message: 'Unhandled Rejection at:',
  timestamp: '2025-06-23 02:57:21'
}
